# Generated by Django 3.1.2 on 2020-11-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrevSearches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.TextField(blank=True, null=True)),
                ('spotifyUID', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prev_search',
            },
        ),
    ]
