# Generated by Django 3.1.2 on 2020-11-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viber', '0002_friends_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friends',
            new_name='Following',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='friendFrom',
            new_name='currentUser',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='friendTo',
            new_name='followingUID',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='person_id',
            new_name='spotifyUID',
        ),
        migrations.RemoveField(
            model_name='person',
            name='spotifyID',
        ),
        migrations.AlterModelTable(
            name='following',
            table='following',
        ),
    ]
